- name: Build, Test & SonarCloud Analysis
  run: mvn clean verify sonar:sonar \
    -Dsonar.projectKey=Amalab1_MPISI \
    -Dsonar.organization=amalab1-1 \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
